//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeAccessData
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountHolderDetail
    {
        public int Id { get; set; }
        public string Bank_Name { get; set; }
        public string Account_Number { get; set; }
        public string Customer_Name { get; set; }
        public string Date_of_Birth { get; set; }
        public string Father_Name { get; set; }
        public string Gender { get; set; }
        public string PAN { get; set; }
        public string Aadhaar { get; set; }
        public string CIF_Id { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Pin_Code { get; set; }
        public string Email_Id { get; set; }
        public string Mobile_Number { get; set; }
        public string Nominee_Name { get; set; }
        public string Nature_of_Account { get; set; }
        public string Type_of_Account { get; set; }
        public string Scheme_Code { get; set; }
        public string Identification_proof_Document_Id { get; set; }
        public string Identification_proof_Document_Name { get; set; }
        public string Address_proof_Document_Id { get; set; }
        public string Address_proof_Document_Name { get; set; }
    }
}
